# development deployment
#appRegion: us-east-1
#appStage: dev
#appName: my-retail-api
#
#productTable: productTableDev

# production deployment
appRegion: us-east-1
appStage: prod
appName: my-retail-api

productTable: productTable

